# Generated by Django 5.1.4 on 2025-01-01 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Задача')),
                ('annotation', models.TextField(blank=True, null=True, verbose_name='Описание задачи')),
                ('status', models.CharField(blank=True, choices=[('CREATED', 'Создана'), ('WORK', 'В работе'), ('POSTPONED', 'Отложено'), ('READY', 'Выполнено')], default='CREATED', max_length=9, null=True)),
                ('is_group', models.BooleanField(default=False, verbose_name='Это группа')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tasks', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
            },
        ),
    ]
