# Generated by Django 5.1.4 on 2025-01-01 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sending_Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_for_send', models.TimeField(blank=True, null=True, verbose_name='Время рассылки задачи')),
                ('period', models.CharField(blank=True, choices=[('DAILY', 'Ежедневно'), ('WEEKLY', 'Еженедельно'), ('MONTHLY', 'Ежемесячно'), ('YEARLY', 'Ежегодно'), ('CUSTOM_DAY', 'В определенный день')], default='WEEKLY', max_length=19, null=True, verbose_name='Периодичность рассылки задачи')),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Активна'), ('STOP', 'Завершена'), ('PAUSE', 'Остановлена')], default='ACTIVE', max_length=11, null=True, verbose_name='Статус рассылки задачи')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tasks', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
